<?php

/* ORMENTITYANNOTATION:Bitrix\Intranet\UserTable */
namespace Bitrix\Intranet {
	/**
	 * EO_User
	 * @see \Bitrix\Intranet\UserTable
	 *
	 * Custom methods:
	 * ---------------
	 *
	 * @method \string getUfDepartment()
	 * @method \string remindActualUfDepartment()
	 * @method \string requireUfDepartment()
	 * @method bool hasUfDepartment()
	 * @method bool isUfDepartmentFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfDepartment()
	 * @method \string fillUfDepartment()
	 * @method \Bitrix\Intranet\EO_User setUfDepartment(\string[] $ufDepartment)
	 * @method bool isUfDepartmentChanged()
	 * @method \string getUfPhoneInner()
	 * @method \string remindActualUfPhoneInner()
	 * @method \string requireUfPhoneInner()
	 * @method bool hasUfPhoneInner()
	 * @method bool isUfPhoneInnerFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfPhoneInner()
	 * @method \string fillUfPhoneInner()
	 * @method \Bitrix\Intranet\EO_User setUfPhoneInner(\string $ufPhoneInner)
	 * @method bool isUfPhoneInnerChanged()
	 * @method \string getUfUserCrmEntity()
	 * @method \string remindActualUfUserCrmEntity()
	 * @method \string requireUfUserCrmEntity()
	 * @method bool hasUfUserCrmEntity()
	 * @method bool isUfUserCrmEntityFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfUserCrmEntity()
	 * @method \string fillUfUserCrmEntity()
	 * @method \Bitrix\Intranet\EO_User setUfUserCrmEntity(\string $ufUserCrmEntity)
	 * @method bool isUfUserCrmEntityChanged()
	 * @method \string getUfImSearch()
	 * @method \string remindActualUfImSearch()
	 * @method \string requireUfImSearch()
	 * @method bool hasUfImSearch()
	 * @method bool isUfImSearchFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfImSearch()
	 * @method \string fillUfImSearch()
	 * @method \Bitrix\Intranet\EO_User setUfImSearch(\string $ufImSearch)
	 * @method bool isUfImSearchChanged()
	 * @method \string getUfConnectorMd5()
	 * @method \string remindActualUfConnectorMd5()
	 * @method \string requireUfConnectorMd5()
	 * @method bool hasUfConnectorMd5()
	 * @method bool isUfConnectorMd5Filled()
	 * @method \Bitrix\Intranet\EO_User unsetUfConnectorMd5()
	 * @method \string fillUfConnectorMd5()
	 * @method \Bitrix\Intranet\EO_User setUfConnectorMd5(\string $ufConnectorMd5)
	 * @method bool isUfConnectorMd5Changed()
	 * @method \int getUf1c()
	 * @method \int remindActualUf1c()
	 * @method \int requireUf1c()
	 * @method bool hasUf1c()
	 * @method bool isUf1cFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUf1c()
	 * @method \int fillUf1c()
	 * @method \Bitrix\Intranet\EO_User setUf1c(\int $uf1c)
	 * @method bool isUf1cChanged()
	 * @method \string getUfInn()
	 * @method \string remindActualUfInn()
	 * @method \string requireUfInn()
	 * @method bool hasUfInn()
	 * @method bool isUfInnFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfInn()
	 * @method \string fillUfInn()
	 * @method \Bitrix\Intranet\EO_User setUfInn(\string $ufInn)
	 * @method bool isUfInnChanged()
	 * @method \string getUfDistrict()
	 * @method \string remindActualUfDistrict()
	 * @method \string requireUfDistrict()
	 * @method bool hasUfDistrict()
	 * @method bool isUfDistrictFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfDistrict()
	 * @method \string fillUfDistrict()
	 * @method \Bitrix\Intranet\EO_User setUfDistrict(\string $ufDistrict)
	 * @method bool isUfDistrictChanged()
	 * @method \string getUfSkype()
	 * @method \string remindActualUfSkype()
	 * @method \string requireUfSkype()
	 * @method bool hasUfSkype()
	 * @method bool isUfSkypeFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfSkype()
	 * @method \string fillUfSkype()
	 * @method \Bitrix\Intranet\EO_User setUfSkype(\string $ufSkype)
	 * @method bool isUfSkypeChanged()
	 * @method \string getUfSkypeLink()
	 * @method \string remindActualUfSkypeLink()
	 * @method \string requireUfSkypeLink()
	 * @method bool hasUfSkypeLink()
	 * @method bool isUfSkypeLinkFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfSkypeLink()
	 * @method \string fillUfSkypeLink()
	 * @method \Bitrix\Intranet\EO_User setUfSkypeLink(\string $ufSkypeLink)
	 * @method bool isUfSkypeLinkChanged()
	 * @method \string getUfZoom()
	 * @method \string remindActualUfZoom()
	 * @method \string requireUfZoom()
	 * @method bool hasUfZoom()
	 * @method bool isUfZoomFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfZoom()
	 * @method \string fillUfZoom()
	 * @method \Bitrix\Intranet\EO_User setUfZoom(\string $ufZoom)
	 * @method bool isUfZoomChanged()
	 * @method \string getUfTwitter()
	 * @method \string remindActualUfTwitter()
	 * @method \string requireUfTwitter()
	 * @method bool hasUfTwitter()
	 * @method bool isUfTwitterFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfTwitter()
	 * @method \string fillUfTwitter()
	 * @method \Bitrix\Intranet\EO_User setUfTwitter(\string $ufTwitter)
	 * @method bool isUfTwitterChanged()
	 * @method \string getUfFacebook()
	 * @method \string remindActualUfFacebook()
	 * @method \string requireUfFacebook()
	 * @method bool hasUfFacebook()
	 * @method bool isUfFacebookFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfFacebook()
	 * @method \string fillUfFacebook()
	 * @method \Bitrix\Intranet\EO_User setUfFacebook(\string $ufFacebook)
	 * @method bool isUfFacebookChanged()
	 * @method \string getUfLinkedin()
	 * @method \string remindActualUfLinkedin()
	 * @method \string requireUfLinkedin()
	 * @method bool hasUfLinkedin()
	 * @method bool isUfLinkedinFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfLinkedin()
	 * @method \string fillUfLinkedin()
	 * @method \Bitrix\Intranet\EO_User setUfLinkedin(\string $ufLinkedin)
	 * @method bool isUfLinkedinChanged()
	 * @method \string getUfXing()
	 * @method \string remindActualUfXing()
	 * @method \string requireUfXing()
	 * @method bool hasUfXing()
	 * @method bool isUfXingFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfXing()
	 * @method \string fillUfXing()
	 * @method \Bitrix\Intranet\EO_User setUfXing(\string $ufXing)
	 * @method bool isUfXingChanged()
	 * @method \string getUfWebSites()
	 * @method \string remindActualUfWebSites()
	 * @method \string requireUfWebSites()
	 * @method bool hasUfWebSites()
	 * @method bool isUfWebSitesFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfWebSites()
	 * @method \string fillUfWebSites()
	 * @method \Bitrix\Intranet\EO_User setUfWebSites(\string $ufWebSites)
	 * @method bool isUfWebSitesChanged()
	 * @method \string getUfSkills()
	 * @method \string remindActualUfSkills()
	 * @method \string requireUfSkills()
	 * @method bool hasUfSkills()
	 * @method bool isUfSkillsFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfSkills()
	 * @method \string fillUfSkills()
	 * @method \Bitrix\Intranet\EO_User setUfSkills(\string $ufSkills)
	 * @method bool isUfSkillsChanged()
	 * @method \string getUfInterests()
	 * @method \string remindActualUfInterests()
	 * @method \string requireUfInterests()
	 * @method bool hasUfInterests()
	 * @method bool isUfInterestsFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfInterests()
	 * @method \string fillUfInterests()
	 * @method \Bitrix\Intranet\EO_User setUfInterests(\string $ufInterests)
	 * @method bool isUfInterestsChanged()
	 * @method \Bitrix\Main\Type\Date getUfEmploymentDate()
	 * @method \Bitrix\Main\Type\Date remindActualUfEmploymentDate()
	 * @method \Bitrix\Main\Type\Date requireUfEmploymentDate()
	 * @method bool hasUfEmploymentDate()
	 * @method bool isUfEmploymentDateFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfEmploymentDate()
	 * @method \Bitrix\Main\Type\Date fillUfEmploymentDate()
	 * @method \Bitrix\Intranet\EO_User setUfEmploymentDate(\Bitrix\Main\Type\Date $ufEmploymentDate)
	 * @method bool isUfEmploymentDateChanged()
	 * @method \string getUfWorkBinding()
	 * @method \string remindActualUfWorkBinding()
	 * @method \string requireUfWorkBinding()
	 * @method bool hasUfWorkBinding()
	 * @method bool isUfWorkBindingFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfWorkBinding()
	 * @method \string fillUfWorkBinding()
	 * @method \Bitrix\Intranet\EO_User setUfWorkBinding(\string $ufWorkBinding)
	 * @method bool isUfWorkBindingChanged()
	 * @method \Bitrix\Main\Type\DateTime getUfBxdavexCalsync()
	 * @method \Bitrix\Main\Type\DateTime remindActualUfBxdavexCalsync()
	 * @method \Bitrix\Main\Type\DateTime requireUfBxdavexCalsync()
	 * @method bool hasUfBxdavexCalsync()
	 * @method bool isUfBxdavexCalsyncFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfBxdavexCalsync()
	 * @method \Bitrix\Main\Type\DateTime fillUfBxdavexCalsync()
	 * @method \Bitrix\Intranet\EO_User setUfBxdavexCalsync(\Bitrix\Main\Type\DateTime $ufBxdavexCalsync)
	 * @method bool isUfBxdavexCalsyncChanged()
	 * @method \int getUfTimeman()
	 * @method \int remindActualUfTimeman()
	 * @method \int requireUfTimeman()
	 * @method bool hasUfTimeman()
	 * @method bool isUfTimemanFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfTimeman()
	 * @method \int fillUfTimeman()
	 * @method \Bitrix\Intranet\EO_User setUfTimeman(\int $ufTimeman)
	 * @method bool isUfTimemanChanged()
	 * @method \string getUfTmMaxStart()
	 * @method \string remindActualUfTmMaxStart()
	 * @method \string requireUfTmMaxStart()
	 * @method bool hasUfTmMaxStart()
	 * @method bool isUfTmMaxStartFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfTmMaxStart()
	 * @method \string fillUfTmMaxStart()
	 * @method \Bitrix\Intranet\EO_User setUfTmMaxStart(\string $ufTmMaxStart)
	 * @method bool isUfTmMaxStartChanged()
	 * @method \string getUfTmMinFinish()
	 * @method \string remindActualUfTmMinFinish()
	 * @method \string requireUfTmMinFinish()
	 * @method bool hasUfTmMinFinish()
	 * @method bool isUfTmMinFinishFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfTmMinFinish()
	 * @method \string fillUfTmMinFinish()
	 * @method \Bitrix\Intranet\EO_User setUfTmMinFinish(\string $ufTmMinFinish)
	 * @method bool isUfTmMinFinishChanged()
	 * @method \string getUfTmMinDuration()
	 * @method \string remindActualUfTmMinDuration()
	 * @method \string requireUfTmMinDuration()
	 * @method bool hasUfTmMinDuration()
	 * @method bool isUfTmMinDurationFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfTmMinDuration()
	 * @method \string fillUfTmMinDuration()
	 * @method \Bitrix\Intranet\EO_User setUfTmMinDuration(\string $ufTmMinDuration)
	 * @method bool isUfTmMinDurationChanged()
	 * @method \int getUfTmReportReq()
	 * @method \int remindActualUfTmReportReq()
	 * @method \int requireUfTmReportReq()
	 * @method bool hasUfTmReportReq()
	 * @method bool isUfTmReportReqFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfTmReportReq()
	 * @method \int fillUfTmReportReq()
	 * @method \Bitrix\Intranet\EO_User setUfTmReportReq(\int $ufTmReportReq)
	 * @method bool isUfTmReportReqChanged()
	 * @method \string getUfTmReportTpl()
	 * @method \string remindActualUfTmReportTpl()
	 * @method \string requireUfTmReportTpl()
	 * @method bool hasUfTmReportTpl()
	 * @method bool isUfTmReportTplFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfTmReportTpl()
	 * @method \string fillUfTmReportTpl()
	 * @method \Bitrix\Intranet\EO_User setUfTmReportTpl(\string[] $ufTmReportTpl)
	 * @method bool isUfTmReportTplChanged()
	 * @method \int getUfTmFree()
	 * @method \int remindActualUfTmFree()
	 * @method \int requireUfTmFree()
	 * @method bool hasUfTmFree()
	 * @method bool isUfTmFreeFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfTmFree()
	 * @method \int fillUfTmFree()
	 * @method \Bitrix\Intranet\EO_User setUfTmFree(\int $ufTmFree)
	 * @method bool isUfTmFreeChanged()
	 * @method \string getUfTmTime()
	 * @method \string remindActualUfTmTime()
	 * @method \string requireUfTmTime()
	 * @method bool hasUfTmTime()
	 * @method bool isUfTmTimeFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfTmTime()
	 * @method \string fillUfTmTime()
	 * @method \Bitrix\Intranet\EO_User setUfTmTime(\string $ufTmTime)
	 * @method bool isUfTmTimeChanged()
	 * @method \string getUfTmDay()
	 * @method \string remindActualUfTmDay()
	 * @method \string requireUfTmDay()
	 * @method bool hasUfTmDay()
	 * @method bool isUfTmDayFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfTmDay()
	 * @method \string fillUfTmDay()
	 * @method \Bitrix\Intranet\EO_User setUfTmDay(\string $ufTmDay)
	 * @method bool isUfTmDayChanged()
	 * @method \string getUfTmReportDate()
	 * @method \string remindActualUfTmReportDate()
	 * @method \string requireUfTmReportDate()
	 * @method bool hasUfTmReportDate()
	 * @method bool isUfTmReportDateFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfTmReportDate()
	 * @method \string fillUfTmReportDate()
	 * @method \Bitrix\Intranet\EO_User setUfTmReportDate(\string $ufTmReportDate)
	 * @method bool isUfTmReportDateChanged()
	 * @method \int getUfReportPeriod()
	 * @method \int remindActualUfReportPeriod()
	 * @method \int requireUfReportPeriod()
	 * @method bool hasUfReportPeriod()
	 * @method bool isUfReportPeriodFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfReportPeriod()
	 * @method \int fillUfReportPeriod()
	 * @method \Bitrix\Intranet\EO_User setUfReportPeriod(\int $ufReportPeriod)
	 * @method bool isUfReportPeriodChanged()
	 * @method \string getUfDelayTime()
	 * @method \string remindActualUfDelayTime()
	 * @method \string requireUfDelayTime()
	 * @method bool hasUfDelayTime()
	 * @method bool isUfDelayTimeFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfDelayTime()
	 * @method \string fillUfDelayTime()
	 * @method \Bitrix\Intranet\EO_User setUfDelayTime(\string $ufDelayTime)
	 * @method bool isUfDelayTimeChanged()
	 * @method \string getUfLastReportDate()
	 * @method \string remindActualUfLastReportDate()
	 * @method \string requireUfLastReportDate()
	 * @method bool hasUfLastReportDate()
	 * @method bool isUfLastReportDateFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfLastReportDate()
	 * @method \string fillUfLastReportDate()
	 * @method \Bitrix\Intranet\EO_User setUfLastReportDate(\string $ufLastReportDate)
	 * @method bool isUfLastReportDateChanged()
	 * @method \string getUfSettingDate()
	 * @method \string remindActualUfSettingDate()
	 * @method \string requireUfSettingDate()
	 * @method bool hasUfSettingDate()
	 * @method bool isUfSettingDateFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfSettingDate()
	 * @method \string fillUfSettingDate()
	 * @method \Bitrix\Intranet\EO_User setUfSettingDate(\string $ufSettingDate)
	 * @method bool isUfSettingDateChanged()
	 * @method \string getUfTmAllowedDelta()
	 * @method \string remindActualUfTmAllowedDelta()
	 * @method \string requireUfTmAllowedDelta()
	 * @method bool hasUfTmAllowedDelta()
	 * @method bool isUfTmAllowedDeltaFilled()
	 * @method \Bitrix\Intranet\EO_User unsetUfTmAllowedDelta()
	 * @method \string fillUfTmAllowedDelta()
	 * @method \Bitrix\Intranet\EO_User setUfTmAllowedDelta(\string $ufTmAllowedDelta)
	 * @method bool isUfTmAllowedDeltaChanged()
	 */
	class EO_User {
		/* @var \Bitrix\Intranet\UserTable */
		static public $dataClass = '\Bitrix\Intranet\UserTable';
		/**
		 * @param bool|array $setDefaultValues
		 */
		public function __construct($setDefaultValues = true) {}
	}
}
namespace Bitrix\Intranet {
	/**
	 * EO_User_Collection
	 *
	 * Custom methods:
	 * ---------------
	 *
	 * @method \string[] getUfDepartmentList()
	 * @method \string[] fillUfDepartment()
	 * @method \string[] getUfPhoneInnerList()
	 * @method \string[] fillUfPhoneInner()
	 * @method \string[] getUfUserCrmEntityList()
	 * @method \string[] fillUfUserCrmEntity()
	 * @method \string[] getUfImSearchList()
	 * @method \string[] fillUfImSearch()
	 * @method \string[] getUfConnectorMd5List()
	 * @method \string[] fillUfConnectorMd5()
	 * @method \int[] getUf1cList()
	 * @method \int[] fillUf1c()
	 * @method \string[] getUfInnList()
	 * @method \string[] fillUfInn()
	 * @method \string[] getUfDistrictList()
	 * @method \string[] fillUfDistrict()
	 * @method \string[] getUfSkypeList()
	 * @method \string[] fillUfSkype()
	 * @method \string[] getUfSkypeLinkList()
	 * @method \string[] fillUfSkypeLink()
	 * @method \string[] getUfZoomList()
	 * @method \string[] fillUfZoom()
	 * @method \string[] getUfTwitterList()
	 * @method \string[] fillUfTwitter()
	 * @method \string[] getUfFacebookList()
	 * @method \string[] fillUfFacebook()
	 * @method \string[] getUfLinkedinList()
	 * @method \string[] fillUfLinkedin()
	 * @method \string[] getUfXingList()
	 * @method \string[] fillUfXing()
	 * @method \string[] getUfWebSitesList()
	 * @method \string[] fillUfWebSites()
	 * @method \string[] getUfSkillsList()
	 * @method \string[] fillUfSkills()
	 * @method \string[] getUfInterestsList()
	 * @method \string[] fillUfInterests()
	 * @method \Bitrix\Main\Type\Date[] getUfEmploymentDateList()
	 * @method \Bitrix\Main\Type\Date[] fillUfEmploymentDate()
	 * @method \string[] getUfWorkBindingList()
	 * @method \string[] fillUfWorkBinding()
	 * @method \Bitrix\Main\Type\DateTime[] getUfBxdavexCalsyncList()
	 * @method \Bitrix\Main\Type\DateTime[] fillUfBxdavexCalsync()
	 * @method \int[] getUfTimemanList()
	 * @method \int[] fillUfTimeman()
	 * @method \string[] getUfTmMaxStartList()
	 * @method \string[] fillUfTmMaxStart()
	 * @method \string[] getUfTmMinFinishList()
	 * @method \string[] fillUfTmMinFinish()
	 * @method \string[] getUfTmMinDurationList()
	 * @method \string[] fillUfTmMinDuration()
	 * @method \int[] getUfTmReportReqList()
	 * @method \int[] fillUfTmReportReq()
	 * @method \string[] getUfTmReportTplList()
	 * @method \string[] fillUfTmReportTpl()
	 * @method \int[] getUfTmFreeList()
	 * @method \int[] fillUfTmFree()
	 * @method \string[] getUfTmTimeList()
	 * @method \string[] fillUfTmTime()
	 * @method \string[] getUfTmDayList()
	 * @method \string[] fillUfTmDay()
	 * @method \string[] getUfTmReportDateList()
	 * @method \string[] fillUfTmReportDate()
	 * @method \int[] getUfReportPeriodList()
	 * @method \int[] fillUfReportPeriod()
	 * @method \string[] getUfDelayTimeList()
	 * @method \string[] fillUfDelayTime()
	 * @method \string[] getUfLastReportDateList()
	 * @method \string[] fillUfLastReportDate()
	 * @method \string[] getUfSettingDateList()
	 * @method \string[] fillUfSettingDate()
	 * @method \string[] getUfTmAllowedDeltaList()
	 * @method \string[] fillUfTmAllowedDelta()
	 */
	class EO_User_Collection implements \ArrayAccess, \Iterator, \Countable {
		/* @var \Bitrix\Intranet\UserTable */
		static public $dataClass = '\Bitrix\Intranet\UserTable';
	}
}
/* ORMENTITYANNOTATION:Bitrix\Main\UserTable */
namespace Bitrix\Main {
	/**
	 * EO_User
	 * @see \Bitrix\Main\UserTable
	 *
	 * Custom methods:
	 * ---------------
	 *
	 * @method \string getUfDepartment()
	 * @method \string remindActualUfDepartment()
	 * @method \string requireUfDepartment()
	 * @method bool hasUfDepartment()
	 * @method bool isUfDepartmentFilled()
	 * @method \Bitrix\Main\EO_User unsetUfDepartment()
	 * @method \string fillUfDepartment()
	 * @method \Bitrix\Main\EO_User setUfDepartment(\string[] $ufDepartment)
	 * @method bool isUfDepartmentChanged()
	 * @method \string getUfPhoneInner()
	 * @method \string remindActualUfPhoneInner()
	 * @method \string requireUfPhoneInner()
	 * @method bool hasUfPhoneInner()
	 * @method bool isUfPhoneInnerFilled()
	 * @method \Bitrix\Main\EO_User unsetUfPhoneInner()
	 * @method \string fillUfPhoneInner()
	 * @method \Bitrix\Main\EO_User setUfPhoneInner(\string $ufPhoneInner)
	 * @method bool isUfPhoneInnerChanged()
	 * @method \string getUfUserCrmEntity()
	 * @method \string remindActualUfUserCrmEntity()
	 * @method \string requireUfUserCrmEntity()
	 * @method bool hasUfUserCrmEntity()
	 * @method bool isUfUserCrmEntityFilled()
	 * @method \Bitrix\Main\EO_User unsetUfUserCrmEntity()
	 * @method \string fillUfUserCrmEntity()
	 * @method \Bitrix\Main\EO_User setUfUserCrmEntity(\string $ufUserCrmEntity)
	 * @method bool isUfUserCrmEntityChanged()
	 * @method \string getUfImSearch()
	 * @method \string remindActualUfImSearch()
	 * @method \string requireUfImSearch()
	 * @method bool hasUfImSearch()
	 * @method bool isUfImSearchFilled()
	 * @method \Bitrix\Main\EO_User unsetUfImSearch()
	 * @method \string fillUfImSearch()
	 * @method \Bitrix\Main\EO_User setUfImSearch(\string $ufImSearch)
	 * @method bool isUfImSearchChanged()
	 * @method \string getUfConnectorMd5()
	 * @method \string remindActualUfConnectorMd5()
	 * @method \string requireUfConnectorMd5()
	 * @method bool hasUfConnectorMd5()
	 * @method bool isUfConnectorMd5Filled()
	 * @method \Bitrix\Main\EO_User unsetUfConnectorMd5()
	 * @method \string fillUfConnectorMd5()
	 * @method \Bitrix\Main\EO_User setUfConnectorMd5(\string $ufConnectorMd5)
	 * @method bool isUfConnectorMd5Changed()
	 * @method \int getUf1c()
	 * @method \int remindActualUf1c()
	 * @method \int requireUf1c()
	 * @method bool hasUf1c()
	 * @method bool isUf1cFilled()
	 * @method \Bitrix\Main\EO_User unsetUf1c()
	 * @method \int fillUf1c()
	 * @method \Bitrix\Main\EO_User setUf1c(\int $uf1c)
	 * @method bool isUf1cChanged()
	 * @method \string getUfInn()
	 * @method \string remindActualUfInn()
	 * @method \string requireUfInn()
	 * @method bool hasUfInn()
	 * @method bool isUfInnFilled()
	 * @method \Bitrix\Main\EO_User unsetUfInn()
	 * @method \string fillUfInn()
	 * @method \Bitrix\Main\EO_User setUfInn(\string $ufInn)
	 * @method bool isUfInnChanged()
	 * @method \string getUfDistrict()
	 * @method \string remindActualUfDistrict()
	 * @method \string requireUfDistrict()
	 * @method bool hasUfDistrict()
	 * @method bool isUfDistrictFilled()
	 * @method \Bitrix\Main\EO_User unsetUfDistrict()
	 * @method \string fillUfDistrict()
	 * @method \Bitrix\Main\EO_User setUfDistrict(\string $ufDistrict)
	 * @method bool isUfDistrictChanged()
	 * @method \string getUfSkype()
	 * @method \string remindActualUfSkype()
	 * @method \string requireUfSkype()
	 * @method bool hasUfSkype()
	 * @method bool isUfSkypeFilled()
	 * @method \Bitrix\Main\EO_User unsetUfSkype()
	 * @method \string fillUfSkype()
	 * @method \Bitrix\Main\EO_User setUfSkype(\string $ufSkype)
	 * @method bool isUfSkypeChanged()
	 * @method \string getUfSkypeLink()
	 * @method \string remindActualUfSkypeLink()
	 * @method \string requireUfSkypeLink()
	 * @method bool hasUfSkypeLink()
	 * @method bool isUfSkypeLinkFilled()
	 * @method \Bitrix\Main\EO_User unsetUfSkypeLink()
	 * @method \string fillUfSkypeLink()
	 * @method \Bitrix\Main\EO_User setUfSkypeLink(\string $ufSkypeLink)
	 * @method bool isUfSkypeLinkChanged()
	 * @method \string getUfZoom()
	 * @method \string remindActualUfZoom()
	 * @method \string requireUfZoom()
	 * @method bool hasUfZoom()
	 * @method bool isUfZoomFilled()
	 * @method \Bitrix\Main\EO_User unsetUfZoom()
	 * @method \string fillUfZoom()
	 * @method \Bitrix\Main\EO_User setUfZoom(\string $ufZoom)
	 * @method bool isUfZoomChanged()
	 * @method \string getUfTwitter()
	 * @method \string remindActualUfTwitter()
	 * @method \string requireUfTwitter()
	 * @method bool hasUfTwitter()
	 * @method bool isUfTwitterFilled()
	 * @method \Bitrix\Main\EO_User unsetUfTwitter()
	 * @method \string fillUfTwitter()
	 * @method \Bitrix\Main\EO_User setUfTwitter(\string $ufTwitter)
	 * @method bool isUfTwitterChanged()
	 * @method \string getUfFacebook()
	 * @method \string remindActualUfFacebook()
	 * @method \string requireUfFacebook()
	 * @method bool hasUfFacebook()
	 * @method bool isUfFacebookFilled()
	 * @method \Bitrix\Main\EO_User unsetUfFacebook()
	 * @method \string fillUfFacebook()
	 * @method \Bitrix\Main\EO_User setUfFacebook(\string $ufFacebook)
	 * @method bool isUfFacebookChanged()
	 * @method \string getUfLinkedin()
	 * @method \string remindActualUfLinkedin()
	 * @method \string requireUfLinkedin()
	 * @method bool hasUfLinkedin()
	 * @method bool isUfLinkedinFilled()
	 * @method \Bitrix\Main\EO_User unsetUfLinkedin()
	 * @method \string fillUfLinkedin()
	 * @method \Bitrix\Main\EO_User setUfLinkedin(\string $ufLinkedin)
	 * @method bool isUfLinkedinChanged()
	 * @method \string getUfXing()
	 * @method \string remindActualUfXing()
	 * @method \string requireUfXing()
	 * @method bool hasUfXing()
	 * @method bool isUfXingFilled()
	 * @method \Bitrix\Main\EO_User unsetUfXing()
	 * @method \string fillUfXing()
	 * @method \Bitrix\Main\EO_User setUfXing(\string $ufXing)
	 * @method bool isUfXingChanged()
	 * @method \string getUfWebSites()
	 * @method \string remindActualUfWebSites()
	 * @method \string requireUfWebSites()
	 * @method bool hasUfWebSites()
	 * @method bool isUfWebSitesFilled()
	 * @method \Bitrix\Main\EO_User unsetUfWebSites()
	 * @method \string fillUfWebSites()
	 * @method \Bitrix\Main\EO_User setUfWebSites(\string $ufWebSites)
	 * @method bool isUfWebSitesChanged()
	 * @method \string getUfSkills()
	 * @method \string remindActualUfSkills()
	 * @method \string requireUfSkills()
	 * @method bool hasUfSkills()
	 * @method bool isUfSkillsFilled()
	 * @method \Bitrix\Main\EO_User unsetUfSkills()
	 * @method \string fillUfSkills()
	 * @method \Bitrix\Main\EO_User setUfSkills(\string $ufSkills)
	 * @method bool isUfSkillsChanged()
	 * @method \string getUfInterests()
	 * @method \string remindActualUfInterests()
	 * @method \string requireUfInterests()
	 * @method bool hasUfInterests()
	 * @method bool isUfInterestsFilled()
	 * @method \Bitrix\Main\EO_User unsetUfInterests()
	 * @method \string fillUfInterests()
	 * @method \Bitrix\Main\EO_User setUfInterests(\string $ufInterests)
	 * @method bool isUfInterestsChanged()
	 * @method \Bitrix\Main\Type\Date getUfEmploymentDate()
	 * @method \Bitrix\Main\Type\Date remindActualUfEmploymentDate()
	 * @method \Bitrix\Main\Type\Date requireUfEmploymentDate()
	 * @method bool hasUfEmploymentDate()
	 * @method bool isUfEmploymentDateFilled()
	 * @method \Bitrix\Main\EO_User unsetUfEmploymentDate()
	 * @method \Bitrix\Main\Type\Date fillUfEmploymentDate()
	 * @method \Bitrix\Main\EO_User setUfEmploymentDate(\Bitrix\Main\Type\Date $ufEmploymentDate)
	 * @method bool isUfEmploymentDateChanged()
	 * @method \string getUfWorkBinding()
	 * @method \string remindActualUfWorkBinding()
	 * @method \string requireUfWorkBinding()
	 * @method bool hasUfWorkBinding()
	 * @method bool isUfWorkBindingFilled()
	 * @method \Bitrix\Main\EO_User unsetUfWorkBinding()
	 * @method \string fillUfWorkBinding()
	 * @method \Bitrix\Main\EO_User setUfWorkBinding(\string $ufWorkBinding)
	 * @method bool isUfWorkBindingChanged()
	 * @method \Bitrix\Main\Type\DateTime getUfBxdavexCalsync()
	 * @method \Bitrix\Main\Type\DateTime remindActualUfBxdavexCalsync()
	 * @method \Bitrix\Main\Type\DateTime requireUfBxdavexCalsync()
	 * @method bool hasUfBxdavexCalsync()
	 * @method bool isUfBxdavexCalsyncFilled()
	 * @method \Bitrix\Main\EO_User unsetUfBxdavexCalsync()
	 * @method \Bitrix\Main\Type\DateTime fillUfBxdavexCalsync()
	 * @method \Bitrix\Main\EO_User setUfBxdavexCalsync(\Bitrix\Main\Type\DateTime $ufBxdavexCalsync)
	 * @method bool isUfBxdavexCalsyncChanged()
	 * @method \int getUfTimeman()
	 * @method \int remindActualUfTimeman()
	 * @method \int requireUfTimeman()
	 * @method bool hasUfTimeman()
	 * @method bool isUfTimemanFilled()
	 * @method \Bitrix\Main\EO_User unsetUfTimeman()
	 * @method \int fillUfTimeman()
	 * @method \Bitrix\Main\EO_User setUfTimeman(\int $ufTimeman)
	 * @method bool isUfTimemanChanged()
	 * @method \string getUfTmMaxStart()
	 * @method \string remindActualUfTmMaxStart()
	 * @method \string requireUfTmMaxStart()
	 * @method bool hasUfTmMaxStart()
	 * @method bool isUfTmMaxStartFilled()
	 * @method \Bitrix\Main\EO_User unsetUfTmMaxStart()
	 * @method \string fillUfTmMaxStart()
	 * @method \Bitrix\Main\EO_User setUfTmMaxStart(\string $ufTmMaxStart)
	 * @method bool isUfTmMaxStartChanged()
	 * @method \string getUfTmMinFinish()
	 * @method \string remindActualUfTmMinFinish()
	 * @method \string requireUfTmMinFinish()
	 * @method bool hasUfTmMinFinish()
	 * @method bool isUfTmMinFinishFilled()
	 * @method \Bitrix\Main\EO_User unsetUfTmMinFinish()
	 * @method \string fillUfTmMinFinish()
	 * @method \Bitrix\Main\EO_User setUfTmMinFinish(\string $ufTmMinFinish)
	 * @method bool isUfTmMinFinishChanged()
	 * @method \string getUfTmMinDuration()
	 * @method \string remindActualUfTmMinDuration()
	 * @method \string requireUfTmMinDuration()
	 * @method bool hasUfTmMinDuration()
	 * @method bool isUfTmMinDurationFilled()
	 * @method \Bitrix\Main\EO_User unsetUfTmMinDuration()
	 * @method \string fillUfTmMinDuration()
	 * @method \Bitrix\Main\EO_User setUfTmMinDuration(\string $ufTmMinDuration)
	 * @method bool isUfTmMinDurationChanged()
	 * @method \int getUfTmReportReq()
	 * @method \int remindActualUfTmReportReq()
	 * @method \int requireUfTmReportReq()
	 * @method bool hasUfTmReportReq()
	 * @method bool isUfTmReportReqFilled()
	 * @method \Bitrix\Main\EO_User unsetUfTmReportReq()
	 * @method \int fillUfTmReportReq()
	 * @method \Bitrix\Main\EO_User setUfTmReportReq(\int $ufTmReportReq)
	 * @method bool isUfTmReportReqChanged()
	 * @method \string getUfTmReportTpl()
	 * @method \string remindActualUfTmReportTpl()
	 * @method \string requireUfTmReportTpl()
	 * @method bool hasUfTmReportTpl()
	 * @method bool isUfTmReportTplFilled()
	 * @method \Bitrix\Main\EO_User unsetUfTmReportTpl()
	 * @method \string fillUfTmReportTpl()
	 * @method \Bitrix\Main\EO_User setUfTmReportTpl(\string[] $ufTmReportTpl)
	 * @method bool isUfTmReportTplChanged()
	 * @method \int getUfTmFree()
	 * @method \int remindActualUfTmFree()
	 * @method \int requireUfTmFree()
	 * @method bool hasUfTmFree()
	 * @method bool isUfTmFreeFilled()
	 * @method \Bitrix\Main\EO_User unsetUfTmFree()
	 * @method \int fillUfTmFree()
	 * @method \Bitrix\Main\EO_User setUfTmFree(\int $ufTmFree)
	 * @method bool isUfTmFreeChanged()
	 * @method \string getUfTmTime()
	 * @method \string remindActualUfTmTime()
	 * @method \string requireUfTmTime()
	 * @method bool hasUfTmTime()
	 * @method bool isUfTmTimeFilled()
	 * @method \Bitrix\Main\EO_User unsetUfTmTime()
	 * @method \string fillUfTmTime()
	 * @method \Bitrix\Main\EO_User setUfTmTime(\string $ufTmTime)
	 * @method bool isUfTmTimeChanged()
	 * @method \string getUfTmDay()
	 * @method \string remindActualUfTmDay()
	 * @method \string requireUfTmDay()
	 * @method bool hasUfTmDay()
	 * @method bool isUfTmDayFilled()
	 * @method \Bitrix\Main\EO_User unsetUfTmDay()
	 * @method \string fillUfTmDay()
	 * @method \Bitrix\Main\EO_User setUfTmDay(\string $ufTmDay)
	 * @method bool isUfTmDayChanged()
	 * @method \string getUfTmReportDate()
	 * @method \string remindActualUfTmReportDate()
	 * @method \string requireUfTmReportDate()
	 * @method bool hasUfTmReportDate()
	 * @method bool isUfTmReportDateFilled()
	 * @method \Bitrix\Main\EO_User unsetUfTmReportDate()
	 * @method \string fillUfTmReportDate()
	 * @method \Bitrix\Main\EO_User setUfTmReportDate(\string $ufTmReportDate)
	 * @method bool isUfTmReportDateChanged()
	 * @method \int getUfReportPeriod()
	 * @method \int remindActualUfReportPeriod()
	 * @method \int requireUfReportPeriod()
	 * @method bool hasUfReportPeriod()
	 * @method bool isUfReportPeriodFilled()
	 * @method \Bitrix\Main\EO_User unsetUfReportPeriod()
	 * @method \int fillUfReportPeriod()
	 * @method \Bitrix\Main\EO_User setUfReportPeriod(\int $ufReportPeriod)
	 * @method bool isUfReportPeriodChanged()
	 * @method \string getUfDelayTime()
	 * @method \string remindActualUfDelayTime()
	 * @method \string requireUfDelayTime()
	 * @method bool hasUfDelayTime()
	 * @method bool isUfDelayTimeFilled()
	 * @method \Bitrix\Main\EO_User unsetUfDelayTime()
	 * @method \string fillUfDelayTime()
	 * @method \Bitrix\Main\EO_User setUfDelayTime(\string $ufDelayTime)
	 * @method bool isUfDelayTimeChanged()
	 * @method \string getUfLastReportDate()
	 * @method \string remindActualUfLastReportDate()
	 * @method \string requireUfLastReportDate()
	 * @method bool hasUfLastReportDate()
	 * @method bool isUfLastReportDateFilled()
	 * @method \Bitrix\Main\EO_User unsetUfLastReportDate()
	 * @method \string fillUfLastReportDate()
	 * @method \Bitrix\Main\EO_User setUfLastReportDate(\string $ufLastReportDate)
	 * @method bool isUfLastReportDateChanged()
	 * @method \string getUfSettingDate()
	 * @method \string remindActualUfSettingDate()
	 * @method \string requireUfSettingDate()
	 * @method bool hasUfSettingDate()
	 * @method bool isUfSettingDateFilled()
	 * @method \Bitrix\Main\EO_User unsetUfSettingDate()
	 * @method \string fillUfSettingDate()
	 * @method \Bitrix\Main\EO_User setUfSettingDate(\string $ufSettingDate)
	 * @method bool isUfSettingDateChanged()
	 * @method \string getUfTmAllowedDelta()
	 * @method \string remindActualUfTmAllowedDelta()
	 * @method \string requireUfTmAllowedDelta()
	 * @method bool hasUfTmAllowedDelta()
	 * @method bool isUfTmAllowedDeltaFilled()
	 * @method \Bitrix\Main\EO_User unsetUfTmAllowedDelta()
	 * @method \string fillUfTmAllowedDelta()
	 * @method \Bitrix\Main\EO_User setUfTmAllowedDelta(\string $ufTmAllowedDelta)
	 * @method bool isUfTmAllowedDeltaChanged()
	 */
	class EO_User {
		/* @var \Bitrix\Main\UserTable */
		static public $dataClass = '\Bitrix\Main\UserTable';
		/**
		 * @param bool|array $setDefaultValues
		 */
		public function __construct($setDefaultValues = true) {}
	}
}
namespace Bitrix\Main {
	/**
	 * EO_User_Collection
	 *
	 * Custom methods:
	 * ---------------
	 *
	 * @method \string[] getUfDepartmentList()
	 * @method \string[] fillUfDepartment()
	 * @method \string[] getUfPhoneInnerList()
	 * @method \string[] fillUfPhoneInner()
	 * @method \string[] getUfUserCrmEntityList()
	 * @method \string[] fillUfUserCrmEntity()
	 * @method \string[] getUfImSearchList()
	 * @method \string[] fillUfImSearch()
	 * @method \string[] getUfConnectorMd5List()
	 * @method \string[] fillUfConnectorMd5()
	 * @method \int[] getUf1cList()
	 * @method \int[] fillUf1c()
	 * @method \string[] getUfInnList()
	 * @method \string[] fillUfInn()
	 * @method \string[] getUfDistrictList()
	 * @method \string[] fillUfDistrict()
	 * @method \string[] getUfSkypeList()
	 * @method \string[] fillUfSkype()
	 * @method \string[] getUfSkypeLinkList()
	 * @method \string[] fillUfSkypeLink()
	 * @method \string[] getUfZoomList()
	 * @method \string[] fillUfZoom()
	 * @method \string[] getUfTwitterList()
	 * @method \string[] fillUfTwitter()
	 * @method \string[] getUfFacebookList()
	 * @method \string[] fillUfFacebook()
	 * @method \string[] getUfLinkedinList()
	 * @method \string[] fillUfLinkedin()
	 * @method \string[] getUfXingList()
	 * @method \string[] fillUfXing()
	 * @method \string[] getUfWebSitesList()
	 * @method \string[] fillUfWebSites()
	 * @method \string[] getUfSkillsList()
	 * @method \string[] fillUfSkills()
	 * @method \string[] getUfInterestsList()
	 * @method \string[] fillUfInterests()
	 * @method \Bitrix\Main\Type\Date[] getUfEmploymentDateList()
	 * @method \Bitrix\Main\Type\Date[] fillUfEmploymentDate()
	 * @method \string[] getUfWorkBindingList()
	 * @method \string[] fillUfWorkBinding()
	 * @method \Bitrix\Main\Type\DateTime[] getUfBxdavexCalsyncList()
	 * @method \Bitrix\Main\Type\DateTime[] fillUfBxdavexCalsync()
	 * @method \int[] getUfTimemanList()
	 * @method \int[] fillUfTimeman()
	 * @method \string[] getUfTmMaxStartList()
	 * @method \string[] fillUfTmMaxStart()
	 * @method \string[] getUfTmMinFinishList()
	 * @method \string[] fillUfTmMinFinish()
	 * @method \string[] getUfTmMinDurationList()
	 * @method \string[] fillUfTmMinDuration()
	 * @method \int[] getUfTmReportReqList()
	 * @method \int[] fillUfTmReportReq()
	 * @method \string[] getUfTmReportTplList()
	 * @method \string[] fillUfTmReportTpl()
	 * @method \int[] getUfTmFreeList()
	 * @method \int[] fillUfTmFree()
	 * @method \string[] getUfTmTimeList()
	 * @method \string[] fillUfTmTime()
	 * @method \string[] getUfTmDayList()
	 * @method \string[] fillUfTmDay()
	 * @method \string[] getUfTmReportDateList()
	 * @method \string[] fillUfTmReportDate()
	 * @method \int[] getUfReportPeriodList()
	 * @method \int[] fillUfReportPeriod()
	 * @method \string[] getUfDelayTimeList()
	 * @method \string[] fillUfDelayTime()
	 * @method \string[] getUfLastReportDateList()
	 * @method \string[] fillUfLastReportDate()
	 * @method \string[] getUfSettingDateList()
	 * @method \string[] fillUfSettingDate()
	 * @method \string[] getUfTmAllowedDeltaList()
	 * @method \string[] fillUfTmAllowedDelta()
	 */
	class EO_User_Collection implements \ArrayAccess, \Iterator, \Countable {
		/* @var \Bitrix\Main\UserTable */
		static public $dataClass = '\Bitrix\Main\UserTable';
	}
}